### ISSUE TITLE
road to v4.0.0

### ISSUE THREAD

**Issue by scttcper** [angulartics/angulartics2#164]
Hello! @JonnyBGod was gracious enough to add me as a contributor. Please discuss the items below or suggest more. v4 will bring a big reduction in bundle size, github pages/docs similar to Angulartics 1 and support for using no router and ui-router. A few things will still make it in under the v3.x.x tag.

__Development Branch__:
https://github.com/angulartics/angulartics2/tree/next
__Install from__:
`npm install angulartics2@next`

#### core
- [x] reduce bundle size #130
- [x] rxjs minimum ^5.5.0 and lettable operators #166
- [x] easier settings #170
- [ ] support without `@angular/router`
- [ ] support [ui-router](https://ui-router.github.io/ng2/)
- [ ] get access to publish under `@angulartics` on npm
- [ ] ionic?
- [ ] nativescript?
- [ ] remove needing to import/construct in root component?
#### providers
- [x] new providers
    - [x] GA enhanced ecommerce #102 *released in 3.0.0*
    - [x] woopra #103 *released in 3.1.0*
    - [x] clicky #172 v4
#### docs
- [x] v3 to v4 migration instructions
- [x] home page
- [x] core
- [x] providers

Update: looks like semantic-release decides to bump the major version for commits and comments inside squashed commits. New to semantic-release. This is now on track for v4. Going to have to watch a tutorial or something.

**Comment by scttcper** [comment]
Docs landing page is up. https://angulartics.github.io/angulartics2/
I think for the providers I want to link to the provider folder and use github readme's in each folder. Easier for contributions

**Comment by scttcper** [comment]
publishing on next branch. Install using `npm install angulartics2@next`

**Comment by scttcper** [comment]
Will open issues for outstanding features on v5. PR open https://github.com/angulartics/angulartics2/pull/175
